config/routes.rb
Rails.application.routes.draw do
  resources :offers, only: :index

  root 'offers#index'
end

app/models/presenters/sponsor_pay/offer.rb
module Presenters::SponsorPay
  class Offer
    attr_reader :title, :payout, :thumbnail_high, :thumbnail_low

    def initialize(hash)
      hash.each do |key, value|
        instance_variable_set("@#{key}", value)
      end
    end

    def thumbnail_high
      @thumbnail[:hires]
    end

    def thumbnail_low
      @thumbnail[:lowres]
    end
  end
end

app/models/remote/client.rb
require 'typhoeus/adapters/faraday'

module Remote
  class Client
    attr_reader :connection

    def initialize
      @connection = Faraday.new do |f|
        f.adapter :typhoeus
        f.use Faraday::Response::RaiseError
        f.options.timeout = timeout
        f.options.open_timeout = open_timeout
      end
    end

    def self.get(url, opts = {})
      new.get(url, opts)
    end

    def get(url, opts= {})
      send_request(url, :get, opts)
    end

    private

    def send_request(url, method, opts)
      begin
        response = nil
        response_time = benchmark { response = connection.send(method, url, opts[:query]) }

        { response: Remote::Response.new(response), response_time: response_time }
      rescue Faraday::Error::TimeoutError, Timeout::Error
        { error: 'Request timeout' }
      rescue Faraday::Error => e
        error_message = e.message

        error_description = try_to_parse_erroneous_response(e.response)
        { error: "#{error_message} (#{error_description})" }
      rescue Errno::ETIMEDOUT, Errno::EHOSTUNREACH, Errno::ECONNRESET, Errno::ECONNREFUSED, EOFError => e
        { error: e.message }
      end
    end

    def benchmark(&block)
      time = Benchmark.measure(&block)
      (time.real * 1000).round(2)
    end

    def timeout
      SponsorPaySettings.timeout || 2
    end

    def open_timeout
      SponsorPaySettings.open_timeout || 2
    end

    # Ideally any response even with 400 status should contain json in its body,
    # but unexpected responses like '502 Bad Gateway' probably will have plain text in body.
    # So we try to parse json body and in cases of plain text error message contains exception's message.
    def try_to_parse_erroneous_response(response)
      if response[:body].present?
        parsed = Oj.load(response[:body], mode: :compat)
        if parsed.is_a?(Hash)
          parsed.values.join(', ')
        else
          parsed
        end
      end
    rescue Oj::ParseError
      nil
    end
  end
end

app/models/remote/response.rb
module Remote
  class Response < SimpleDelegator
    def decode_json
      begin
        Oj.load(body, mode: :compat, symbol_keys: true)
      rescue Oj::ParseError
        nil
      end
    end
  end
end

app/models/remote/sponsor_pay/offers_request.rb
module Remote::SponsorPay
  class OffersRequest
    include ::ActiveModel::Validations

    attr_reader :uid, :pub0, :page, :params

    validates :uid, presence: true
    validates :page, numericality: { only_integer: true, greater_than: 0, allow_blank: true }

    def initialize(uid, pub0 = '', page = 1)
      @uid  = uid
      @pub0 = pub0
      @page = page

      @params = build_params
    end

    def self.perform(uid, pub0 = '', page = 1)
      new(uid, pub0, page).perform
    end

    def perform
      # Pass params as part of URL string because Faraday escapes spaces in params using `+`.
      answer = Remote::Client.get("#{url}?#{params}")
      response = answer[:response]

      if response && response.status == 200
        signature = Digest::SHA1.hexdigest("#{response.body}#{api_key}")
        if response.headers['X-Sponsorpay-Response-Signature'] == signature
          if parsed_body = response.decode_json
            offers = Array(parsed_body[:offers]).map { |hash| Presenters::SponsorPay::Offer.new(hash) }
            answer.slice(:response_time).merge(offers: offers)
          else
            { error: 'Malformed response body' }
          end
        else
          { error: 'Signature error' }
        end
      else
        { error: answer[:error] }
      end
    end

    private

    # The trick is `to_query` method escapes space as plus `+` symbol, but it seems SponsorPay API expects space escaped as `%20`.
    # CGI module uses plus to escape/unescape space, while URI uses `%20` to escape/unescape space.
    def build_params
      params = { uid: uid, pub0: pub0, page: page, timestamp: Time.zone.now.to_i }.merge(SponsorPaySettings.app_params.symbolize_keys)

      # First transform hash to sorted query and unescape string using CGI to remove potential `+` symbols.
      joined_params = CGI.unescape(params.to_query)

      # Then make a hashkey.
      hashkey = Digest::SHA1.hexdigest("#{joined_params}&#{api_key}")

      # And finally make final query with escaped spaces as `%20`.
      "#{URI.escape(joined_params)}&hashkey=#{hashkey}"
    end

    def api_key
      SponsorPaySettings.api_key
    end

    def url
      SponsorPaySettings.url
    end
  end
end

app/models/sponsor_pay_settings.rb
class SponsorPaySettings < Settingslogic
  source "#{Rails.root}/config/sponsor_pay.yml"
  namespace Rails.env
  suppress_errors Rails.env.production?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  def index
    if (query = params['query']).present?
      offers_request = Remote::SponsorPay::OffersRequest.new(query[:uid], query[:pub0], query[:page])

      if offers_request.valid?
        @offers, error, @response_time = offers_request.perform.values_at(:offers, :error, :response_time)
        @errors = Array(error)
      else
        @errors = offers_request.errors.full_messages
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SpTask</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/offers/_offers.html.erb
<% if offers.present? %>
  <div class='offers-table'>
    <div class='offer heading'>
      <div class='title col'>Offer Title</div>
      <div class='payout col'>Offer Payout</div>
      <div class='thumbnail col'>Offer Thumbnail</div>
    </div>

    <% offers.each do |offer| %>
      <div class='offer row'>
        <div class='title col'><%= offer.title %></div>
        <div class='payout col'><%= offer.payout %></div>
        <div class='thumbnail col'><%= image_tag(offer.thumbnail_low) %></div>
      </div>
      <% end %>
    </div>
  </div>
<% else %>
  <div class='no_offers info'>No offers</div>
<% end %>

app/views/offers/_response_time.html.erb
<% if @response_time %>
  <div class='response_time'>
    Request to SponsorPay took: <%= @response_time %> ms.
  </div><br>
<% end %>

app/views/offers/index.html.erb
<h1><%= link_to 'Offers', offers_path %></h1>

<%= form_tag offers_path, method: :get do %>
  <%= label_tag(:uid,  'uid:')  %> <%= text_field_tag('query[uid]',  params[:query].try(:[], 'uid'))  %>
  <%= label_tag(:pub0, 'pub0:') %> <%= text_field_tag('query[pub0]', params[:query].try(:[], 'pub0')) %>
  <%= label_tag(:page, 'page:') %> <%= text_field_tag('query[page]', params[:query].try(:[], 'page')) %>

  <%= submit_tag('Fetch offers') %>
<% end %>

<br><hr>

<% if params[:query].present? %>
  <% if @errors.present? %>
    <div class='error'>
      Got the following errors: <br> <%= raw @errors.join('<br/>') %>
    </div>
  <% else %>
    <%= render partial: 'response_time' %> <br>

    <%= render partial: 'offers', locals: { offers: @offers } %>
  <% end %>
<% end %>